### ISSUE TITLE
Question re: safety

### ISSUE THREAD

**Issue by fwsGonzo** [dougallj/zlib-dougallj#2]
Hey, I am using your libz changes in a sandbox, where I am not particularly interested in safety features. Are there any safety features like bounds-checking etc. that could cause performance slowdowns?

**Comment by dougallj** [comment]
Nothing expensive comes to mind. There are checks you could remove, but I wouldn't expect a measurable performance difference, because they predict well and aren't on the critical path.

To maximise unsafety you could try changing `in < last && out < end` to `1` in `inffast_chunk.c`. That's in the hot loop. Note that removing bounds checks breaks all incremental decompression APIs. (And if you don't need API compatibility, I'd probably use [libdeflate](https://github.com/ebiggers/libdeflate) instead)
 
There are "close to end of buffer checks" (`INFLATE_FAST_MIN_OUTPUT = 260` and `INFLATE_FAST_MIN_INPUT = 17`) that start using the slow path for the last few bytes, but if you pad both your input and output buffers by those amounts you get the speedup without needing to remove safety checks (and removing those would break non-one-shot APIs).

I also don't think the `used > ENOUGH_LENS` and `used > ENOUGH_DISTS` checks in `inftrees.c` are necessary, but again, wouldn't expect any difference by removing them.

**Comment by fwsGonzo** [comment]
Thanks! I'll give those ideas a try :)
